# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
